name: V2Ray Server
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  run-v2ray:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install V2Ray
        run: |
          sudo apt update
          sudo apt install -y curl
          bash <(curl -L https://github.com/v2fly/v2ray-core/releases/download/v5.16.1/install-release.sh)
      - name: Configure V2Ray
        run: |
          cat <<EOF > /usr/local/etc/v2ray/config.json
          {
            "inbounds": [{
              "port": 10000,
              "protocol": "vless",
              "settings": {
                "clients": [
                  {
                    "id": "50ff51bd-3763-4c12-b011-2ec1732fd931",
                    "level": 0
                  }
                ],
                "decryption": "none"
              },
              "streamSettings": {
                "network": "tcp"
              }
            }],
            "outbounds": [{
              "protocol": "freedom",
              "settings": {}
            }]
          }
          EOF
      - name: Run V2Ray
        run: |
          /usr/local/bin/v2ray run -c /usr/local/etc/v2ray/config.json &
          sleep 3600
